apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: c-1-{{ .Values.environment }}
  namespace: argocd 
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: "c-1-{{ .Values.environment }}"
    server: '*'
  sourceRepos:
  - '*' 
