apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jupyter
  namespace: argocd
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/shuffleSoftware/argo.git
      revision: main
      files:
        # first wildcard: name of application
        # second wildcard: client
        # third wildcard: actual deployment replica
        - path: apps/appset/**/**/{{ .Values.environment }}/**/values.yaml
  template:
    metadata:
      name: '{{ "{{path[2]}}-{{path[3]}}-{{path[4]}}-{{path[5]}}" }}'
      labels:
        app: '{{ "{{path[2]}}" }}'
    spec:
      project: '{{ "{{path[3]}}-{{path[4]}}" }}'
      source:
        repoURL: https://github.com/shuffleSoftware/argo.git
        targetRevision: main
        path: '{{ "{{path}}" }}'
        helm:
          parameters:
          - name: "app"
            value: '{{ "{{path[2]}}-{{path[5]}}" }}'
          - name: "namespace"
            value: '{{ "{{path[3]}}-{{path[4]}}" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{path[3]}}-{{path[4]}}" }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true  
